(function(){
'use strict';
const DB=window.BFDB,U=window.BFU,$=s=>document.querySelector(s),view=$('#view');
const state={data:{},route:'dashboard',masterTab:'items',draftIn:null,draftOut:null};
const masterDefs={
 items:{title:'Barang',singular:'Barang',fields:[['name','Nama Barang','text'],['code','Kode','text'],['category','Kategori','text']]},
 customers:{title:'Customer',singular:'Customer',fields:[['name','Nama Customer','text'],['phone','Telepon','text'],['address','Alamat','textarea']]},
 suppliers:{title:'Supplier',singular:'Supplier',fields:[['name','Nama Supplier','text'],['phone','Telepon','text'],['address','Alamat','textarea']]},
 drivers:{title:'Supir',singular:'Supir',fields:[['name','Nama Supir','text'],['phone','Telepon','text'],['vehicle','Kendaraan','text']]},
 units:{title:'Satuan',singular:'Satuan',fields:[['name','Nama Satuan','text'],['symbol','Singkatan','text']]}
};
function toast(msg,type=''){const el=document.createElement('div');el.className='toast '+type;el.textContent=msg;$('#toastHost').appendChild(el);setTimeout(()=>el.remove(),3200)}
function modal(html){$('#modalHost').innerHTML=`<div class="modal-wrap" id="modalWrap"><div class="modal">${html}</div></div>`;$('#modalWrap').addEventListener('click',e=>{if(e.target.id==='modalWrap')closeModal()})}
function closeModal(){$('#modalHost').innerHTML=''} window.closeModal=closeModal;
async function load(){for(const s of DB.stores) state.data[s]=await DB.all(s);await ensureSeed();}
async function ensureSeed(){if(!state.data.units?.length){for(const x of [{id:'unit_kg',name:'Kilogram',symbol:'kg',active:true},{id:'unit_pcs',name:'Pcs',symbol:'pcs',active:true},{id:'unit_box',name:'Box',symbol:'box',active:true}]) await DB.put('units',x);state.data.units=await DB.all('units')}}
function active(list){return (list||[]).filter(x=>x.active!==false).sort((a,b)=>(a.name||'').localeCompare(b.name||''))}
function byId(store,id){return (state.data[store]||[]).find(x=>x.id===id)}
function name(store,id){return byId(store,id)?.name||'(data tidak ditemukan)'}
function opts(store,selected='',placeholder='Pilih'){return `<option value="">${placeholder}</option>`+active(state.data[store]).map(x=>`<option value="${U.esc(x.id)}" ${x.id===selected?'selected':''}>${U.esc(x.name)}${x.symbol?` (${U.esc(x.symbol)})`:''}</option>`).join('')}
function route(){const hash=(location.hash||'#/dashboard').replace('#/','').split('?')[0];const allowed=['dashboard','incoming','outgoing','stock','transactions','reports','master','settings'];state.route=allowed.includes(hash)?hash:'dashboard';document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===state.route));render().catch(showFatal);closeSide();}
function closeSide(){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')}
function pageHead(title,sub,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`}
function empty(msg='Belum ada data'){return `<div class="empty">${msg}</div>`}
function numTransactionsToday(list){const t=U.today();return (list||[]).filter(x=>x.date===t).length}
function totalWeight(entries){return U.sum(entries||[],e=>U.sum(e.weights||[]))}
function itemWeightIn(tx,itemId){return U.sum((tx.items||[]).filter(i=>i.itemId===itemId),i=>U.sum(i.weights||[]))}
function outgoingItems(tx){return (tx.customers||[]).flatMap(c=>c.items||[])}
function stockMap(){const m={};for(const it of state.data.items||[])m[it.id]=0;for(const tx of state.data.incoming||[])for(const i of tx.items||[])m[i.itemId]=(m[i.itemId]||0)+U.sum(i.weights||[]);for(const tx of state.data.outgoing||[])for(const i of outgoingItems(tx))m[i.itemId]=(m[i.itemId]||0)-U.sum(i.weights||[]);for(const a of state.data.adjustments||[])m[a.itemId]=(m[a.itemId]||0)+U.num(a.qty);return m}
async function log(action,detail){const row={id:U.id('log'),action,detail,createdAt:U.now()};await DB.put('logs',row);state.data.logs.unshift(row)}
async function refresh(){await load();await render();toast('Data dimuat ulang','ok')}

async function render(){switch(state.route){case'dashboard':return renderDashboard();case'incoming':return renderIncoming();case'outgoing':return renderOutgoing();case'stock':return renderStock();case'transactions':return renderTransactions();case'reports':return renderReports();case'master':return renderMaster();case'settings':return renderSettings();}}
function renderDashboard(){const sm=stockMap(),low=Object.entries(sm).filter(([,v])=>v<=0).length;const recent=[...(state.data.incoming||[]).map(x=>({...x,kind:'Masuk'})),...(state.data.outgoing||[]).map(x=>({...x,kind:'Keluar'})),...(state.data.notes||[]).map(x=>({...x,kind:'Catatan'}))].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')).slice(0,8);
view.innerHTML=pageHead('Dashboard','Ringkasan operasional Bintang Frozen hari ini')+`<div class="grid cards"><div class="card metric"><span>Barang Masuk Hari Ini</span><strong>${numTransactionsToday(state.data.incoming)}</strong></div><div class="card metric"><span>Barang Keluar Hari Ini</span><strong>${numTransactionsToday(state.data.outgoing)}</strong></div><div class="card metric"><span>Master Barang</span><strong>${active(state.data.items).length}</strong></div><div class="card metric"><span>Stok ≤ 0</span><strong class="${low?'danger-text':''}">${low}</strong></div></div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Aktivitas Terbaru</h2></div>${recent.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Waktu</th><th>Jenis</th><th>Keterangan</th></tr></thead><tbody>${recent.map(r=>`<tr><td>${U.date(r.createdAt)}</td><td><span class="pill muted">${r.kind}</span></td><td>${r.kind==='Masuk'?`${U.esc(r.number)} · ${U.esc(name('suppliers',r.supplierId))}`:r.kind==='Keluar'?U.esc(r.number):U.esc(r.text||'-')}</td></tr>`).join('')}</tbody></table></div>`:empty('Belum ada aktivitas.')}</div>`}

function renderIncoming(){const rows=[...(state.data.incoming||[])].sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));view.innerHTML=pageHead('Barang Masuk','Catat penerimaan barang dan timbangan real',`<button class="btn primary" id="newIncoming">+ Barang Masuk</button>`)+`<div class="card"><div class="searchbar"><input id="searchIn" placeholder="Cari nomor, supplier, keterangan…"></div><div id="incomingList">${incomingTable(rows)}</div></div>`;$('#newIncoming').onclick=()=>openIncomingForm();$('#searchIn').oninput=e=>{const q=e.target.value.toLowerCase();$('#incomingList').innerHTML=incomingTable(rows.filter(r=>[r.number,name('suppliers',r.supplierId),r.note].join(' ').toLowerCase().includes(q)));bindIncomingRows()};bindIncomingRows()}
function incomingTable(rows){return rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Nomor</th><th>Supplier</th><th>Item</th><th>Total Timbang</th><th>Ongkir</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${U.date(r.date)}</td><td><strong>${U.esc(r.number)}</strong></td><td>${U.esc(name('suppliers',r.supplierId))}</td><td>${(r.items||[]).length}</td><td>${U.qty(totalWeight(r.items))} kg</td><td>${U.money(r.shippingCost)}</td><td><button class="btn small ghost in-detail" data-id="${r.id}">Detail</button></td></tr>`).join('')}</tbody></table></div>`:empty()}
function bindIncomingRows(){document.querySelectorAll('.in-detail').forEach(b=>b.onclick=()=>showIncoming(b.dataset.id))}
function txNumber(prefix,list){const d=U.today().replaceAll('-','');const count=(list||[]).filter(x=>(x.date||'').replaceAll('-','')===d).length+1;return `${prefix}-${d}-${String(count).padStart(4,'0')}`}
function openIncomingForm(existing){state.draftIn=existing?JSON.parse(JSON.stringify(existing)):{id:U.id('in'),number:txNumber('BM',state.data.incoming),date:U.today(),supplierId:'',driverId:'',shippingCost:0,note:'',photo:'',items:[],createdAt:U.now(),updatedAt:U.now()};renderIncomingModal()}
function renderIncomingModal(){const d=state.draftIn;modal(`<h2>${state.data.incoming.some(x=>x.id===d.id)?'Edit':'Tambah'} Barang Masuk</h2><div class="form-grid cols-2"><div class="field"><label>Nomor</label><input id="inNumber" value="${U.esc(d.number)}"></div><div class="field"><label>Tanggal</label><input id="inDate" type="date" value="${d.date}"></div><div class="field"><label>Supplier *</label><select id="inSupplier">${opts('suppliers',d.supplierId,'Pilih supplier')}</select></div><div class="field"><label>Supir</label><select id="inDriver">${opts('drivers',d.driverId,'Pilih supir')}</select></div><div class="field"><label>Ongkos Kirim</label><input id="inShip" type="number" min="0" value="${d.shippingCost||0}"></div><div class="field"><label>Foto Nota</label><input id="inPhoto" type="file" accept="image/*"><span class="hint">Opsional. Dikompres oleh browser bila perangkat melakukannya.</span></div></div><div class="divider"></div><div class="section-title"><h2>Item & Tally</h2><button class="btn small primary" id="addInItem">+ Item</button></div><div id="inItems">${renderIncomingItems(d.items)}</div><div class="field" style="margin-top:12px"><label>Keterangan</label><textarea id="inNote">${U.esc(d.note)}</textarea></div><div class="actions" style="margin-top:16px"><button class="btn primary" id="saveIn">Simpan</button><button class="btn" onclick="closeModal()">Batal</button></div>`);$('#addInItem').onclick=()=>{captureIncoming();d.items.push({id:U.id('ini'),itemId:'',unitId:'unit_kg',weights:[]});renderIncomingModal()};bindIncomingItemEvents();$('#saveIn').onclick=saveIncoming;}
function renderIncomingItems(items){return items.length?items.map((i,idx)=>`<div class="item-box" data-idx="${idx}"><div class="form-grid cols-3"><div class="field"><label>Barang *</label><select class="ini-item">${opts('items',i.itemId,'Pilih barang')}</select></div><div class="field"><label>Satuan</label><select class="ini-unit">${opts('units',i.unitId,'Pilih satuan')}</select></div><div class="field"><label>Tambah Timbangan</label><div class="actions"><input class="ini-weight" type="number" step="0.01" placeholder="kg" style="min-width:0;flex:1"><button class="btn small add-weight">Tambah</button></div></div></div><div class="weights">${(i.weights||[]).map((w,widx)=>`<span class="weight-chip">${U.qty(w)} <button class="rm-weight" data-w="${widx}">×</button></span>`).join('')}</div><div class="summary-line"><span>${i.weights.length} timbangan</span><strong>${U.qty(U.sum(i.weights))} kg</strong></div><button class="btn small danger rm-in-item" style="margin-top:8px">Hapus Item</button></div>`).join(''):empty('Belum ada item. Tekan “+ Item”.')}
function captureIncoming(){const d=state.draftIn;if(!d)return;d.number=$('#inNumber')?.value||d.number;d.date=$('#inDate')?.value||d.date;d.supplierId=$('#inSupplier')?.value||'';d.driverId=$('#inDriver')?.value||'';d.shippingCost=U.num($('#inShip')?.value);d.note=$('#inNote')?.value||'';document.querySelectorAll('#inItems .item-box').forEach((el,idx)=>{if(d.items[idx]){d.items[idx].itemId=el.querySelector('.ini-item').value;d.items[idx].unitId=el.querySelector('.ini-unit').value}})}
function bindIncomingItemEvents(){document.querySelectorAll('#inItems .item-box').forEach((el,idx)=>{el.querySelector('.add-weight').onclick=()=>{captureIncoming();const input=el.querySelector('.ini-weight'),v=U.num(input.value);if(v<=0)return toast('Masukkan berat lebih dari 0','error');state.draftIn.items[idx].weights.push(v);renderIncomingModal()};el.querySelectorAll('.rm-weight').forEach(b=>b.onclick=()=>{captureIncoming();state.draftIn.items[idx].weights.splice(Number(b.dataset.w),1);renderIncomingModal()});el.querySelector('.rm-in-item').onclick=()=>{captureIncoming();state.draftIn.items.splice(idx,1);renderIncomingModal()}})}
async function saveIncoming(){captureIncoming();const d=state.draftIn;if(!d.supplierId)return toast('Supplier wajib dipilih','error');if(!d.items.length||d.items.some(i=>!i.itemId||!i.weights.length))return toast('Setiap item wajib memiliki barang dan minimal 1 timbangan','error');const f=$('#inPhoto')?.files?.[0];if(f){if(f.size>2.5*1024*1024)return toast('Foto nota maksimal 2,5 MB','error');d.photo=await U.fileDataURL(f)}d.updatedAt=U.now();await DB.put('incoming',d);await log('barang_masuk',`${d.number} disimpan`);state.data.incoming=await DB.all('incoming');closeModal();toast('Barang masuk tersimpan','ok');renderIncoming()}
function showIncoming(id){const r=byId('incoming',id);if(!r)return;modal(`<h2>${U.esc(r.number)}</h2><div class="summary-line"><span>Tanggal</span><strong>${U.date(r.date)}</strong></div><div class="summary-line"><span>Supplier</span><strong>${U.esc(name('suppliers',r.supplierId))}</strong></div><div class="summary-line"><span>Supir</span><strong>${U.esc(name('drivers',r.driverId))}</strong></div><div class="summary-line"><span>Ongkir</span><strong>${U.money(r.shippingCost)}</strong></div><div class="divider"></div>${(r.items||[]).map(i=>`<div class="item-box"><strong>${U.esc(name('items',i.itemId))}</strong><div class="weights">${i.weights.map(w=>`<span class="weight-chip">${U.qty(w)}</span>`).join('')}</div><div class="summary-line"><span>Total</span><strong>${U.qty(U.sum(i.weights))} kg</strong></div></div>`).join('')}${r.photo?`<div class="field"><label>Foto Nota</label><img class="photo-preview" src="${r.photo}" alt="Foto nota"></div>`:''}<p>${U.esc(r.note||'')}</p><div class="actions"><button class="btn primary" id="editIn">Edit</button><button class="btn danger" id="delIn">Hapus</button><button class="btn" onclick="closeModal()">Tutup</button></div>`);$('#editIn').onclick=()=>openIncomingForm(r);$('#delIn').onclick=async()=>{if(!confirm('Hapus transaksi barang masuk ini?'))return;await DB.del('incoming',r.id);await log('hapus_barang_masuk',r.number);state.data.incoming=await DB.all('incoming');closeModal();renderIncoming();toast('Transaksi dihapus')}}

function renderOutgoing(){const rows=[...(state.data.outgoing||[])].sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));view.innerHTML=pageHead('Barang Keluar','Catat pesanan multi-customer, multi-item, dan timbangan real',`<button class="btn primary" id="newOutgoing">+ Barang Keluar</button>`)+`<div class="card"><div class="searchbar"><input id="searchOut" placeholder="Cari nomor, customer, keterangan…"></div><div id="outgoingList">${outgoingTable(rows)}</div></div>`;$('#newOutgoing').onclick=()=>openOutgoingForm();$('#searchOut').oninput=e=>{const q=e.target.value.toLowerCase();$('#outgoingList').innerHTML=outgoingTable(rows.filter(r=>[r.number,r.note,...(r.customers||[]).map(c=>name('customers',c.customerId))].join(' ').toLowerCase().includes(q)));bindOutgoingRows()};bindOutgoingRows()}
function outgoingTable(rows){return rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Nomor</th><th>Customer</th><th>Item</th><th>Total Timbang</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${U.date(r.date)}</td><td><strong>${U.esc(r.number)}</strong></td><td>${(r.customers||[]).map(c=>U.esc(name('customers',c.customerId))).join(', ')}</td><td>${outgoingItems(r).length}</td><td>${U.qty(U.sum(outgoingItems(r),i=>U.sum(i.weights||[])))} kg</td><td><button class="btn small ghost out-detail" data-id="${r.id}">Detail</button></td></tr>`).join('')}</tbody></table></div>`:empty()}
function bindOutgoingRows(){document.querySelectorAll('.out-detail').forEach(b=>b.onclick=()=>showOutgoing(b.dataset.id))}
function openOutgoingForm(existing){state.draftOut=existing?JSON.parse(JSON.stringify(existing)):{id:U.id('out'),number:txNumber('BK',state.data.outgoing),date:U.today(),customers:[],note:'',createdAt:U.now(),updatedAt:U.now()};renderOutgoingModal()}
function renderOutgoingModal(){const d=state.draftOut;modal(`<h2>${state.data.outgoing.some(x=>x.id===d.id)?'Edit':'Tambah'} Barang Keluar</h2><div class="form-grid cols-2"><div class="field"><label>Nomor</label><input id="outNumber" value="${U.esc(d.number)}"></div><div class="field"><label>Tanggal</label><input id="outDate" type="date" value="${d.date}"></div></div><div class="divider"></div><div class="section-title"><h2>Customer & Item</h2><button class="btn small primary" id="addCustomer">+ Customer</button></div><div id="outCustomers">${renderCustomers(d.customers)}</div><div class="field" style="margin-top:12px"><label>Keterangan</label><textarea id="outNote">${U.esc(d.note)}</textarea></div><div class="actions" style="margin-top:16px"><button class="btn primary" id="saveOut">Simpan</button><button class="btn" onclick="closeModal()">Batal</button></div>`);$('#addCustomer').onclick=()=>{captureOutgoing();d.customers.push({id:U.id('oc'),customerId:'',items:[]});renderOutgoingModal()};bindOutgoingEvents();$('#saveOut').onclick=saveOutgoing}
function renderCustomers(cs){return cs.length?cs.map((c,ci)=>`<div class="item-box customer-box" data-ci="${ci}"><div class="form-grid cols-2"><div class="field"><label>Customer *</label><select class="oc-customer">${opts('customers',c.customerId,'Pilih customer')}</select></div><div class="actions" style="align-items:end"><button class="btn small primary add-out-item">+ Item</button><button class="btn small danger rm-customer">Hapus Customer</button></div></div><div class="stack">${(c.items||[]).map((i,ii)=>renderOutItem(i,ii)).join('')}</div></div>`).join(''):empty('Belum ada customer. Tekan “+ Customer”.')}
function renderOutItem(i,ii){return `<div class="item-box out-item" data-ii="${ii}"><div class="form-grid cols-3"><div class="field"><label>Barang *</label><select class="oi-item">${opts('items',i.itemId,'Pilih barang')}</select></div><div class="field"><label>Qty Pesanan</label><input class="oi-qty" type="number" step="0.01" value="${i.orderQty||''}" placeholder="Qty"></div><div class="field"><label>Satuan</label><select class="oi-unit">${opts('units',i.unitId||'unit_kg','Satuan')}</select></div></div><div class="field"><label>Tambah Timbangan</label><div class="actions"><input class="oi-weight" type="number" step="0.01" placeholder="kg" style="min-width:0;flex:1"><button class="btn small add-oi-weight">Tambah</button></div></div><div class="weights">${(i.weights||[]).map((w,wi)=>`<span class="weight-chip">${U.qty(w)} <button class="rm-oi-weight" data-wi="${wi}">×</button></span>`).join('')}</div><div class="summary-line"><span>${(i.weights||[]).length} timbangan</span><strong>${U.qty(U.sum(i.weights||[]))} kg</strong></div><button class="btn small danger rm-out-item" style="margin-top:8px">Hapus Item</button></div>`}
function captureOutgoing(){const d=state.draftOut;if(!d)return;d.number=$('#outNumber')?.value||d.number;d.date=$('#outDate')?.value||d.date;d.note=$('#outNote')?.value||'';document.querySelectorAll('#outCustomers .customer-box').forEach((ce,ci)=>{if(!d.customers[ci])return;d.customers[ci].customerId=ce.querySelector('.oc-customer').value;ce.querySelectorAll('.out-item').forEach((ie,ii)=>{const it=d.customers[ci].items[ii];if(it){it.itemId=ie.querySelector('.oi-item').value;it.orderQty=U.num(ie.querySelector('.oi-qty').value);it.unitId=ie.querySelector('.oi-unit').value}})})}
function bindOutgoingEvents(){document.querySelectorAll('#outCustomers .customer-box').forEach((ce,ci)=>{ce.querySelector('.add-out-item').onclick=()=>{captureOutgoing();state.draftOut.customers[ci].items.push({id:U.id('oi'),itemId:'',orderQty:0,unitId:'unit_kg',weights:[]});renderOutgoingModal()};ce.querySelector('.rm-customer').onclick=()=>{captureOutgoing();state.draftOut.customers.splice(ci,1);renderOutgoingModal()};ce.querySelectorAll('.out-item').forEach((ie,ii)=>{ie.querySelector('.add-oi-weight').onclick=()=>{captureOutgoing();const v=U.num(ie.querySelector('.oi-weight').value);if(v<=0)return toast('Masukkan berat lebih dari 0','error');state.draftOut.customers[ci].items[ii].weights.push(v);renderOutgoingModal()};ie.querySelectorAll('.rm-oi-weight').forEach(b=>b.onclick=()=>{captureOutgoing();state.draftOut.customers[ci].items[ii].weights.splice(Number(b.dataset.wi),1);renderOutgoingModal()});ie.querySelector('.rm-out-item').onclick=()=>{captureOutgoing();state.draftOut.customers[ci].items.splice(ii,1);renderOutgoingModal()}})})}
async function saveOutgoing(){captureOutgoing();const d=state.draftOut;if(!d.customers.length||d.customers.some(c=>!c.customerId||!c.items.length||c.items.some(i=>!i.itemId||!i.weights.length)))return toast('Setiap customer wajib memiliki minimal satu item dan timbangan','error');d.updatedAt=U.now();await DB.put('outgoing',d);await log('barang_keluar',`${d.number} disimpan`);state.data.outgoing=await DB.all('outgoing');closeModal();toast('Barang keluar tersimpan','ok');renderOutgoing()}
function showOutgoing(id){const r=byId('outgoing',id);if(!r)return;modal(`<h2>${U.esc(r.number)}</h2><div class="summary-line"><span>Tanggal</span><strong>${U.date(r.date)}</strong></div>${(r.customers||[]).map(c=>`<div class="item-box"><strong>${U.esc(name('customers',c.customerId))}</strong>${(c.items||[]).map(i=>`<div class="summary-line"><span>${U.esc(name('items',i.itemId))} · Pesanan ${U.qty(i.orderQty)} ${U.esc(byId('units',i.unitId)?.symbol||'')}</span><strong>${U.qty(U.sum(i.weights||[]))} kg</strong></div>`).join('')}</div>`).join('')}<p>${U.esc(r.note||'')}</p><div class="actions"><button class="btn primary" id="editOut">Edit</button><button class="btn danger" id="delOut">Hapus</button><button class="btn" onclick="closeModal()">Tutup</button></div>`);$('#editOut').onclick=()=>openOutgoingForm(r);$('#delOut').onclick=async()=>{if(!confirm('Hapus transaksi barang keluar ini?'))return;await DB.del('outgoing',r.id);await log('hapus_barang_keluar',r.number);state.data.outgoing=await DB.all('outgoing');closeModal();renderOutgoing();toast('Transaksi dihapus')}}

function renderStock(){const sm=stockMap(),rows=active(state.data.items).map(i=>({i,qty:sm[i.id]||0}));view.innerHTML=pageHead('Stok','Stok dihitung dari Barang Masuk − Barang Keluar + Penyesuaian',`<button class="btn primary" id="adjustStock">+ Penyesuaian</button>`)+`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Barang</th><th>Kategori</th><th>Stok Aktual</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${U.esc(r.i.name)}</strong></td><td>${U.esc(r.i.category||'-')}</td><td>${U.qty(r.qty)} kg</td><td><span class="pill ${r.qty>0?'ok':'warn'}">${r.qty>0?'Tersedia':'Kosong / Minus'}</span></td></tr>`).join('')}</tbody></table></div></div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Riwayat Penyesuaian</h2></div>${(state.data.adjustments||[]).length?`<div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Barang</th><th>Jumlah</th><th>Alasan</th></tr></thead><tbody>${[...state.data.adjustments].sort((a,b)=>b.date.localeCompare(a.date)).map(a=>`<tr><td>${U.date(a.date)}</td><td>${U.esc(name('items',a.itemId))}</td><td>${a.qty>=0?'+':''}${U.qty(a.qty)} kg</td><td>${U.esc(a.note||'-')}</td></tr>`).join('')}</tbody></table></div>`:empty()}</div>`;$('#adjustStock').onclick=openAdjustment}
function openAdjustment(){modal(`<h2>Penyesuaian Stok</h2><div class="form-grid cols-2"><div class="field"><label>Tanggal</label><input id="adjDate" type="date" value="${U.today()}"></div><div class="field"><label>Barang *</label><select id="adjItem">${opts('items','','Pilih barang')}</select></div><div class="field"><label>Jumlah (kg) *</label><input id="adjQty" type="number" step="0.01" placeholder="Contoh: -2 atau 5"></div><div class="field"><label>Alasan</label><input id="adjNote" placeholder="Stok opname, susut, koreksi…"></div></div><div class="actions" style="margin-top:16px"><button class="btn primary" id="saveAdj">Simpan</button><button class="btn" onclick="closeModal()">Batal</button></div>`);$('#saveAdj').onclick=async()=>{const itemId=$('#adjItem').value,qty=U.num($('#adjQty').value);if(!itemId||qty===0)return toast('Barang dan jumlah wajib diisi','error');const a={id:U.id('adj'),date:$('#adjDate').value,itemId,qty,note:$('#adjNote').value,createdAt:U.now()};await DB.put('adjustments',a);state.data.adjustments=await DB.all('adjustments');await log('penyesuaian_stok',`${name('items',itemId)} ${qty}`);closeModal();renderStock();toast('Penyesuaian tersimpan','ok')}}

function renderTransactions(){const notes=[...(state.data.notes||[])].sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));view.innerHTML=pageHead('Transaksi / Catatan','Buku catatan digital untuk aktivitas operasional',`<button class="btn primary" id="newNote">+ Catatan</button>`)+`<div class="card">${notes.length?notes.map(n=>`<div class="item-box"><div class="section-title"><div><strong>${U.esc(n.title||'Catatan')}</strong><div class="muted">${U.date(n.date)}</div></div><button class="btn small danger del-note" data-id="${n.id}">Hapus</button></div><div>${U.esc(n.text).replace(/\n/g,'<br>')}</div></div>`).join(''):empty('Belum ada catatan operasional.')}</div>`;$('#newNote').onclick=()=>{modal(`<h2>Catatan Operasional</h2><div class="field"><label>Tanggal</label><input id="noteDate" type="date" value="${U.today()}"></div><div class="field"><label>Judul</label><input id="noteTitle" placeholder="Opsional"></div><div class="field"><label>Catatan *</label><textarea id="noteText" placeholder="Tulis kejadian atau informasi operasional…"></textarea></div><div class="actions"><button class="btn primary" id="saveNote">Simpan</button><button class="btn" onclick="closeModal()">Batal</button></div>`);$('#saveNote').onclick=async()=>{const text=$('#noteText').value.trim();if(!text)return toast('Catatan tidak boleh kosong','error');const n={id:U.id('note'),date:$('#noteDate').value,title:$('#noteTitle').value.trim(),text,createdAt:U.now()};await DB.put('notes',n);state.data.notes=await DB.all('notes');await log('catatan','Catatan operasional ditambah');closeModal();renderTransactions();toast('Catatan tersimpan','ok')}};document.querySelectorAll('.del-note').forEach(b=>b.onclick=async()=>{if(!confirm('Hapus catatan ini?'))return;await DB.del('notes',b.dataset.id);state.data.notes=await DB.all('notes');renderTransactions()})}

function renderReports(){const from=new Date();from.setDate(1);const f=from.toISOString().slice(0,10),t=U.today();view.innerHTML=pageHead('Laporan','Ringkasan dari sumber transaksi yang sama')+`<div class="card"><div class="form-grid cols-3"><div class="field"><label>Dari</label><input id="repFrom" type="date" value="${f}"></div><div class="field"><label>Sampai</label><input id="repTo" type="date" value="${t}"></div><div class="field"><label>&nbsp;</label><button class="btn primary" id="runReport">Tampilkan</button></div></div></div><div id="reportResult" style="margin-top:14px"></div>`;$('#runReport').onclick=runReport;runReport()}
function runReport(){const f=$('#repFrom').value,t=$('#repTo').value,ins=(state.data.incoming||[]).filter(x=>x.date>=f&&x.date<=t),outs=(state.data.outgoing||[]).filter(x=>x.date>=f&&x.date<=t);const inW=U.sum(ins,x=>totalWeight(x.items)),outW=U.sum(outs,x=>U.sum(outgoingItems(x),i=>U.sum(i.weights||[])));const per={};for(const it of active(state.data.items))per[it.id]={name:it.name,in:0,out:0};for(const x of ins)for(const i of x.items||[])if(per[i.itemId])per[i.itemId].in+=U.sum(i.weights||[]);for(const x of outs)for(const i of outgoingItems(x))if(per[i.itemId])per[i.itemId].out+=U.sum(i.weights||[]);$('#reportResult').innerHTML=`<div class="grid cards"><div class="card metric"><span>Transaksi Masuk</span><strong>${ins.length}</strong></div><div class="card metric"><span>Berat Masuk</span><strong>${U.qty(inW)} kg</strong></div><div class="card metric"><span>Transaksi Keluar</span><strong>${outs.length}</strong></div><div class="card metric"><span>Berat Keluar</span><strong>${U.qty(outW)} kg</strong></div></div><div class="card" style="margin-top:14px"><div class="section-title"><h2>Pergerakan per Barang</h2><button class="btn small" id="exportCsv">Export CSV</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Barang</th><th>Masuk</th><th>Keluar</th><th>Selisih</th></tr></thead><tbody>${Object.values(per).map(r=>`<tr><td>${U.esc(r.name)}</td><td>${U.qty(r.in)} kg</td><td>${U.qty(r.out)} kg</td><td>${U.qty(r.in-r.out)} kg</td></tr>`).join('')}</tbody></table></div></div>`;$('#exportCsv').onclick=()=>{const rows=[['Barang','Masuk kg','Keluar kg','Selisih kg'],...Object.values(per).map(r=>[r.name,r.in,r.out,r.in-r.out])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');U.download(`laporan-${f}-${t}.csv`,csv,'text/csv')}}

function renderMaster(){const def=masterDefs[state.masterTab],rows=active(state.data[state.masterTab]);view.innerHTML=pageHead('Master Data','Satu sumber data untuk barang, customer, supplier, supir, dan satuan',`<button class="btn primary" id="addMaster">+ ${def.singular}</button>`)+`<div class="tabs">${Object.entries(masterDefs).map(([k,v])=>`<button class="tab ${k===state.masterTab?'active':''}" data-tab="${k}">${v.title}</button>`).join('')}</div><div class="card"><div class="searchbar"><input id="masterSearch" placeholder="Cari ${def.title.toLowerCase()}…"></div><div id="masterList">${masterTable(rows,def)}</div></div>`;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.masterTab=b.dataset.tab;renderMaster()});$('#addMaster').onclick=()=>openMasterForm(state.masterTab);$('#masterSearch').oninput=e=>{const q=e.target.value.toLowerCase();$('#masterList').innerHTML=masterTable(rows.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q)),def);bindMasterRows()};bindMasterRows()}
function masterTable(rows,def){return rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>${def.singular}</th><th>Detail</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${U.esc(r.name)}</strong></td><td>${U.esc(r.code||r.phone||r.symbol||r.category||r.vehicle||r.address||'-')}</td><td><div class="actions"><button class="btn small ghost edit-master" data-id="${r.id}">Edit</button><button class="btn small danger deactivate-master" data-id="${r.id}">Nonaktifkan</button></div></td></tr>`).join('')}</tbody></table></div>`:empty()}
function bindMasterRows(){document.querySelectorAll('.edit-master').forEach(b=>b.onclick=()=>openMasterForm(state.masterTab,byId(state.masterTab,b.dataset.id)));document.querySelectorAll('.deactivate-master').forEach(b=>b.onclick=async()=>{const r=byId(state.masterTab,b.dataset.id);if(!r||!confirm(`Nonaktifkan ${r.name}? Histori transaksi tetap dipertahankan.`))return;r.active=false;r.updatedAt=U.now();await DB.put(state.masterTab,r);state.data[state.masterTab]=await DB.all(state.masterTab);renderMaster();toast('Data dinonaktifkan','ok')})}
function openMasterForm(store,row={}){const def=masterDefs[store];modal(`<h2>${row.id?'Edit':'Tambah'} ${def.singular}</h2><div class="form-grid cols-2">${def.fields.map(([key,label,type])=>`<div class="field"><label>${label}${key==='name'?' *':''}</label>${type==='textarea'?`<textarea data-key="${key}">${U.esc(row[key]||'')}</textarea>`:`<input data-key="${key}" type="${type}" value="${U.esc(row[key]||'')}">`}</div>`).join('')}</div><div class="actions" style="margin-top:16px"><button class="btn primary" id="saveMaster">Simpan</button><button class="btn" onclick="closeModal()">Batal</button></div>`);$('#saveMaster').onclick=async()=>{const obj={...row,id:row.id||U.id(store.slice(0,3)),active:true,createdAt:row.createdAt||U.now(),updatedAt:U.now()};document.querySelectorAll('[data-key]').forEach(el=>obj[el.dataset.key]=el.value.trim());if(!obj.name)return toast('Nama wajib diisi','error');await DB.put(store,obj);state.data[store]=await DB.all(store);await log('master_data',`${def.singular} ${obj.name} disimpan`);closeModal();renderMaster();toast(`${def.singular} tersimpan`,'ok')}}

function renderSettings(){const business=byId('settings','business')||{name:'Bintang Frozen'};view.innerHTML=pageHead('Pengaturan','Identitas aplikasi, backup, restore, dan pemeliharaan data')+`<div class="grid"><div class="card"><div class="section-title"><h2>Identitas</h2></div><div class="form-grid cols-2"><div class="field"><label>Nama Usaha</label><input id="setBusiness" value="${U.esc(business.name||'Bintang Frozen')}"></div><div class="field"><label>Versi</label><input value="V27 Rebuild" disabled></div></div><button class="btn primary" id="saveSettings" style="margin-top:12px">Simpan</button></div><div class="card"><div class="section-title"><h2>Backup & Restore</h2></div><p class="muted">Backup mencakup seluruh master data, transaksi, stok adjustment, catatan, pengaturan, dan foto nota yang tersimpan.</p><div class="actions"><button class="btn primary" id="backupBtn">Download Backup JSON</button><label class="btn" for="restoreFile">Restore Backup</label><input id="restoreFile" type="file" accept="application/json" hidden></div></div><div class="card"><div class="section-title"><h2>Pemeliharaan</h2></div><div class="summary-line"><span>Barang</span><strong>${state.data.items.length}</strong></div><div class="summary-line"><span>Barang Masuk</span><strong>${state.data.incoming.length}</strong></div><div class="summary-line"><span>Barang Keluar</span><strong>${state.data.outgoing.length}</strong></div><div class="summary-line"><span>Catatan</span><strong>${state.data.notes.length}</strong></div><div class="divider"></div><button class="btn danger" id="resetBtn">Hapus Semua Data</button></div></div>`;$('#saveSettings').onclick=async()=>{const x={id:'business',name:$('#setBusiness').value.trim()||'Bintang Frozen',updatedAt:U.now()};await DB.put('settings',x);state.data.settings=await DB.all('settings');$('#businessName').textContent=x.name;toast('Pengaturan tersimpan','ok')};$('#backupBtn').onclick=async()=>{const data=await DB.exportAll();U.download(`bintang-frozen-v27-backup-${U.today()}.json`,JSON.stringify(data,null,2));toast('Backup dibuat','ok')};$('#restoreFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await U.fileText(f));if(!confirm('Restore akan mengganti seluruh data saat ini. Lanjutkan?'))return;await DB.importAll(data);await load();toast('Restore selesai','ok');renderSettings()}catch(err){toast('Restore gagal: '+err.message,'error')}};$('#resetBtn').onclick=async()=>{if(!confirm('PERINGATAN: semua data V27 akan dihapus. Lanjutkan?'))return;if(!confirm('Konfirmasi kedua: data yang belum dibackup tidak dapat dikembalikan.'))return;await DB.resetAll();state.data={};await load();toast('Semua data telah dihapus','ok');renderSettings()}}

function showFatal(err){console.error(err);view.innerHTML=`<div class="error-panel"><h2>Aplikasi tidak dapat membuka halaman ini</h2><p>${U.esc(err?.message||String(err))}</p><p class="muted">Data tidak otomatis dihapus. Anda dapat mencoba memuat ulang halaman.</p><div class="actions"><button class="btn primary" id="fatalReload">Muat Ulang</button><button class="btn" id="fatalDash">Dashboard</button></div></div>`;$('#fatalReload').onclick=()=>location.reload();$('#fatalDash').onclick=()=>{location.hash='#/dashboard'}}
function network(){const on=navigator.onLine;$('#onlineState').textContent=on?'● Online':'● Offline';$('#onlineState').style.color=on?'#86efac':'#fca5a5'}
async function init(){try{if(!('indexedDB'in window))throw new Error('Browser ini tidak mendukung IndexedDB.');await DB.open();await load();const business=byId('settings','business');if(business?.name)$('#businessName').textContent=business.name;window.addEventListener('hashchange',route);$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#backdrop').classList.add('show')};$('#backdrop').onclick=closeSide;$('#refreshBtn').onclick=refresh;window.addEventListener('online',network);window.addEventListener('offline',network);network();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(console.warn);if(!location.hash)location.hash='#/dashboard';else route()}catch(err){showFatal(err)}}
window.addEventListener('error',e=>{console.error('Global error',e.error||e.message)});window.addEventListener('unhandledrejection',e=>{console.error('Unhandled promise',e.reason)});init();
})();
