require('dotenv').config();
const express=require('express'),cors=require('cors'),helmet=require('helmet'),morgan=require('morgan'),PDFDocument=require('pdfkit');
const {createClient}=require('@supabase/supabase-js');
const app=express(); app.use(helmet({contentSecurityPolicy:false})); app.use(cors()); app.use(express.json({limit:'2mb'})); app.use(morgan('tiny')); app.use(express.static('public'));
const admin=createClient(process.env.SUPABASE_URL||'',process.env.SUPABASE_SERVICE_ROLE_KEY||'',{auth:{autoRefreshToken:false,persistSession:false}});
const authClient=createClient(process.env.SUPABASE_URL||'',process.env.SUPABASE_ANON_KEY||'',{auth:{autoRefreshToken:false,persistSession:false}});
function bearer(req){let h=req.headers.authorization||'';return h.startsWith('Bearer ')?h.slice(7):null}
async function auth(req,res,next){try{let t=bearer(req);if(!t)return res.status(401).json({error:'Login diperlukan.'});let {data,error}=await authClient.auth.getUser(t);if(error||!data.user)return res.status(401).json({error:'Token tidak valid.'});let p=await admin.from('profiles').select('id,full_name,role,is_active,phone').eq('id',data.user.id).single();if(p.error||!p.data||!p.data.is_active)return res.status(403).json({error:'Akun tidak aktif.'});req.user=data.user;req.profile=p.data;next()}catch(e){res.status(500).json({error:e.message})}}
const allow=(...r)=>(req,res,next)=>r.includes(req.profile.role)?next():res.status(403).json({error:'Akses ditolak.'});
const fail=(res,e)=>res.status(400).json({error:e.message||String(e)});
async function audit(req,action,type,id,oldData=null,newData=null){try{await admin.from('audit_logs').insert({actor_id:req.profile.id,action,entity_type:type,entity_id:id||null,old_data:oldData,new_data:newData})}catch(e){console.error('audit',e.message)}}
app.get('/api/health',(q,s)=>s.json({ok:true,app:'Bintang Frozen V26',version:'26.0.0'}));
app.get('/api/me',auth,(q,s)=>s.json({user:q.user,profile:q.profile}));
app.get('/api/dashboard',auth,async(q,s)=>{try{let names=['products','customers','inbound_transactions','outbound_transactions','expenses','commissions'];let out={};for(let n of names){let x=await admin.from(n).select('id',{count:'exact',head:true});out[n]=x.count||0}s.json(out)}catch(e){fail(s,e)}});
for(const [name,table] of [['customers','customers'],['suppliers','suppliers'],['products','products']]){app.get('/api/'+name,auth,async(q,s)=>{let x=await admin.from(table).select('*').order('name');if(x.error)return fail(s,x.error);s.json(x.data)});}
app.get('/api/stock',auth,async(q,s)=>{let x=await admin.from('current_stock').select('*').order('name');if(x.error)return fail(s,x.error);s.json(x.data)});
app.get('/api/inbound',auth,async(q,s)=>{let x=await admin.from('inbound_transactions').select('*,suppliers(name),inbound_items(*,products(name,unit),inbound_weighings(*))').order('transaction_date',{ascending:false}).limit(200);if(x.error)return fail(s,x.error);s.json(x.data)});
app.post('/api/inbound',auth,allow('owner','admin','staff'),async(q,s)=>{try{let {supplier_id,driver_name,vehicle_plate,notes,items=[]}=q.body;if(!supplier_id||!items.length)return s.status(400).json({error:'Supplier dan item wajib.'});let no='BM-'+new Date().toISOString().slice(2,10).replaceAll('-','')+'-'+Date.now().toString().slice(-6);let tx=await admin.from('inbound_transactions').insert({transaction_no:no,supplier_id,driver_name,vehicle_plate,notes,status:'completed',created_by:q.profile.id}).select().single();if(tx.error)throw tx.error;let rows=items.map((x,i)=>({inbound_id:tx.data.id,product_id:x.product_id,line_no:i+1,qty:x.qty||0,unit:x.unit||'Kg',purchase_price:x.purchase_price||0,notes:x.notes||null}));let li=await admin.from('inbound_items').insert(rows).select();if(li.error)throw li.error;await audit(q,'CREATE','inbound_transaction',tx.data.id,null,{transaction:tx.data,items:li.data});s.status(201).json({transaction:tx.data,items:li.data})}catch(e){fail(s,e)}});
app.post('/api/inbound/:itemId/weighing',auth,allow('owner','admin','staff'),async(q,s)=>{let c=await admin.from('inbound_weighings').select('id',{count:'exact',head:true}).eq('inbound_item_id',q.params.itemId);let x=await admin.from('inbound_weighings').insert({inbound_item_id:q.params.itemId,weighing_no:(c.count||0)+1,gross_weight:q.body.gross_weight,tare_weight:q.body.tare_weight||0,operator_id:q.profile.id,status:q.body.status||'valid',notes:q.body.notes}).select().single();if(x.error)return fail(s,x.error);await audit(q,'CREATE','inbound_weighing',x.data.id,null,x.data);s.status(201).json(x.data)});
app.get('/api/outbound',auth,async(q,s)=>{let x=await admin.from('outbound_transactions').select('*,customers(name),outbound_items(*,products(name,unit),outbound_weighings(*))').order('transaction_date',{ascending:false}).limit(200);if(x.error)return fail(s,x.error);s.json(x.data)});
app.post('/api/outbound',auth,allow('owner','admin','staff','marketing'),async(q,s)=>{try{let {customer_id,marketing_id,delivery_address,driver_name,vehicle_plate,notes,items=[]}=q.body;if(!customer_id||!items.length)return s.status(400).json({error:'Customer dan item wajib.'});let no='BK-'+new Date().toISOString().slice(2,10).replaceAll('-','')+'-'+Date.now().toString().slice(-6);let tx=await admin.from('outbound_transactions').insert({transaction_no:no,customer_id,marketing_id:marketing_id||null,delivery_address,driver_name,vehicle_plate,notes,status:'completed',created_by:q.profile.id}).select().single();if(tx.error)throw tx.error;let rows=items.map((x,i)=>({outbound_id:tx.data.id,product_id:x.product_id,line_no:i+1,qty:x.qty||0,unit:x.unit||'Kg',selling_price:x.selling_price||0,notes:x.notes||null}));let li=await admin.from('outbound_items').insert(rows).select();if(li.error)throw li.error;await audit(q,'CREATE','outbound_transaction',tx.data.id,null,{transaction:tx.data,items:li.data});s.status(201).json({transaction:tx.data,items:li.data})}catch(e){fail(s,e)}});
app.post('/api/outbound/:itemId/weighing',auth,allow('owner','admin','staff'),async(q,s)=>{let c=await admin.from('outbound_weighings').select('id',{count:'exact',head:true}).eq('outbound_item_id',q.params.itemId);let x=await admin.from('outbound_weighings').insert({outbound_item_id:q.params.itemId,weighing_no:(c.count||0)+1,gross_weight:q.body.gross_weight,tare_weight:q.body.tare_weight||0,operator_id:q.profile.id,status:q.body.status||'valid',notes:q.body.notes}).select().single();if(x.error)return fail(s,x.error);await audit(q,'CREATE','outbound_weighing',x.data.id,null,x.data);s.status(201).json(x.data)});
app.get('/api/finance/payments',auth,allow('owner','admin'),async(q,s)=>{let x=await admin.from('payments').select('*,customers(name),payment_methods(name)').order('payment_date',{ascending:false}).limit(500);if(x.error)return fail(s,x.error);s.json(x.data)});
app.get('/api/finance/expenses',auth,allow('owner','admin'),async(q,s)=>{let x=await admin.from('expenses').select('*,payment_methods(name)').order('expense_date',{ascending:false}).limit(500);if(x.error)return fail(s,x.error);s.json(x.data)});
app.get('/api/commissions',auth,allow('owner','admin','marketing'),async(q,s)=>{let x=await admin.from('commissions').select('*').order('commission_date',{ascending:false}).limit(500);if(x.error)return fail(s,x.error);s.json(x.data)});
app.get('/api/audit',auth,allow('owner','admin'),async(q,s)=>{let x=await admin.from('audit_logs').select('*,profiles(full_name,role)').order('created_at',{ascending:false}).limit(500);if(x.error)return fail(s,x.error);s.json(x.data)});
app.get('/api/reports/summary.pdf',auth,allow('owner','admin'),async(q,s)=>{try{let [i,o,e,c]=await Promise.all([admin.from('inbound_transactions').select('transaction_no,transaction_date,status').order('transaction_date',{ascending:false}).limit(100),admin.from('outbound_transactions').select('transaction_no,transaction_date,status,payment_status').order('transaction_date',{ascending:false}).limit(100),admin.from('expenses').select('expense_no,expense_date,category,description,amount').order('expense_date',{ascending:false}).limit(100),admin.from('commissions').select('commission_no,commission_date,total_kg,total_commission,status').order('commission_date',{ascending:false}).limit(100)]);let d=new PDFDocument({margin:40});s.setHeader('Content-Type','application/pdf');s.setHeader('Content-Disposition','attachment; filename="Bintang-Frozen-Laporan-Gabungan.pdf"');d.pipe(s);d.fontSize(20).text('BINTANG FROZEN',{align:'center'});d.fontSize(13).text('LAPORAN GABUNGAN V26',{align:'center'});d.moveDown();d.fontSize(9).text('Dicetak: '+new Date().toLocaleString('id-ID'));const sec=(title,rows,fn)=>{d.moveDown().fontSize(13).text(title);d.fontSize(8);if(!rows?.length)d.text('Tidak ada data.');else rows.forEach(r=>d.text(fn(r)))};sec('BARANG MASUK',i.data,r=>`${r.transaction_no} | ${r.transaction_date} | ${r.status}`);sec('BARANG KELUAR',o.data,r=>`${r.transaction_no} | ${r.transaction_date} | ${r.status} | ${r.payment_status}`);sec('PENGELUARAN',e.data,r=>`${r.expense_no} | ${r.expense_date} | ${r.category} | Rp ${Number(r.amount||0).toLocaleString('id-ID')} | ${r.description}`);sec('KOMISI',c.data,r=>`${r.commission_no} | ${r.commission_date} | ${r.total_kg} Kg | Rp ${Number(r.total_commission||0).toLocaleString('id-ID')} | ${r.status}`);d.end()}catch(e){fail(s,e)}});
app.get('*',(q,s)=>s.sendFile(require('path').join(__dirname,'public','index.html')));app.listen(process.env.PORT||3000,()=>console.log('Bintang Frozen V26 ready'));
